### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by SimahoJr** [caiofis/RSSI-Localization#1]
Did you write a paper or something?
Please share.

**Comment by caiofis** [comment]
No, it was a freelancing job, not a scientific project. But I can send you some material on email :)

**Comment by SimahoJr** [comment]
Please do!

I will appreciate

from my phone

On 4 Mar 2020, at 21:27, caiofis <notifications@github.com> wrote:

﻿

No, it was a freelancing job, not a scientific project. But I can send you some material on email :)

**Comment by mhcn** [comment]
Hi, caiofis.
 I'm interesting in this project,too.Currently, I'm trying to localize the UHF tags by a reader. Could you please send me some information about it?
Thanks

**Comment by caiofis** [comment]
Hi, sorry but I haven't worked on this topic for a long time, I am probably massively outdated on it
